package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.fx.comp.DefaultFXCView;
import de.ruu.lib.fx.comp.FXCView;

/**
 * Java FX Component {@link Add}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.06.28 10:14:48:197
 */
public class Add extends DefaultFXCView<Add, AddService, AddController> implements FXCView<AddService> { }