package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link AddApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.06.28 10:14:48:230
 */
public class AddApp extends FXCApp { }