package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.cdi.common.CDIUtil;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import javafx.fxml.FXML;
import javafx.scene.control.Button;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.06.28 10:14:48:219
 */
class AddController extends DefaultFXCController<Add, AddService> implements AddService
{
	@FXML private Button btn;

	@Override public Button button() { return btn; }

	@Override @FXML protected void initialize() { CDIUtil.fire(new AddComponentReadyEvent(view(), this)); }
}