package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.comp.FXCService;
import de.ruu.lib.fx.comp.FXComponentReadyEventAbstract;
import jakarta.enterprise.context.ApplicationScoped;
import javafx.scene.control.Button;
import lombok.NonNull;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.06.28 10:14:48:216
 */
public interface AddService extends FXCService
{
	Button button();

	/** Event that is fired to indicate that a {@link Add} component has become available. */
	class AddComponentReadyEvent extends FXComponentReadyEventAbstract<Add, AddService>
	{
		@ApplicationScoped
		public static class AddComponentReadyEventDispatcher extends EventDispatcher<AddComponentReadyEvent>
		{
		}

		public AddComponentReadyEvent(final @NonNull Add add, final @NonNull AddService addService) {
			super(add, addService);
		}

		/** programmatically specify command line vm option {@code --add-reads de.ruu.lib.fx.comp=ALL-UNNAMED} */
		public static void addReadsUnnamedModule()
		{
			AddComponentReadyEvent.class.getModule()
					.addReads(AddComponentReadyEvent.class.getClassLoader().getUnnamedModule());
		}
	}
}