package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.cdi.common.CDIUtil;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import javafx.fxml.FXML;
import javafx.scene.control.Button;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.07.15 08:12:49:337
 */
class EditController extends DefaultFXCController<Edit, EditService> implements EditService
{
	@FXML private Button btnEdit;

	@Override public Button button() { return btnEdit; }

	@Override @FXML protected void initialize() { CDIUtil.fire(new EditComponentReadyEvent(view(), this)); }
}