package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.fx.comp.DefaultFXCView;
import de.ruu.lib.fx.comp.FXCView;

/**
 * Java FX Component {@link Edit}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.07.15 08:12:49:335
 */
public class Edit extends DefaultFXCView<Edit, EditService, EditController> implements FXCView<EditService> { }