package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.comp.FXCService;
import de.ruu.lib.fx.comp.FXComponentReadyEventAbstract;
import jakarta.enterprise.context.ApplicationScoped;
import javafx.scene.control.Button;
import lombok.NonNull;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.07.15 08:12:49:336
 */
public interface EditService extends FXCService
{
	Button button();

	/** Event that is fired to indicate that a {@link Edit} component has become available. */
	public class EditComponentReadyEvent extends FXComponentReadyEventAbstract<Edit, EditService>
	{
		@ApplicationScoped
		public static class EditComponentReadyEventDispatcher extends EventDispatcher<EditComponentReadyEvent>
		{
		}

		public EditComponentReadyEvent(final @NonNull Edit edit, final @NonNull EditService editService) {
			super(edit, editService);
		}

		/** programmatically specify command line vm option {@code --add-reads de.ruu.lib.fx.comp=ALL-UNNAMED} */
		public static void addReadsUnnamedModule()
		{
			EditComponentReadyEvent.class.getModule()
					.addReads(EditComponentReadyEvent.class.getClassLoader().getUnnamedModule());
		}
	}
}