package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link EditApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.07.15 08:12:49:341
 */
public class EditApp extends FXCApp { }