package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.fx.comp.DefaultFXCView;
import de.ruu.lib.fx.comp.FXCView;

/**
 * Java FX Component {@link Remove}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.07.15 08:12:49:325
 */
public class Remove extends DefaultFXCView<Remove, RemoveService, RemoveController> implements FXCView<RemoveService> { }