package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link RemoveApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.07.15 08:12:49:332
 */
public class RemoveApp extends FXCApp { }