package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.cdi.common.CDIUtil;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import javafx.fxml.FXML;
import javafx.scene.control.Button;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.07.15 08:12:49:328
 */
class RemoveController extends DefaultFXCController<Remove, RemoveService> implements RemoveService
{
	@FXML private Button btn;

	@Override public Button button() { return btn; }

	@Override @FXML protected void initialize() { CDIUtil.fire(new RemoveComponentReadyEvent(view(), this)); }
}