package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.comp.FXCService;
import de.ruu.lib.fx.comp.FXComponentReadyEventAbstract;
import jakarta.enterprise.context.ApplicationScoped;
import javafx.scene.control.Button;
import lombok.NonNull;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.07.15 08:12:49:326
 */
public interface RemoveService extends FXCService
{
	Button button();

	/** Event that is fired to indicate that a {@link Add} component has become available. */
	class RemoveComponentReadyEvent extends FXComponentReadyEventAbstract<Remove, RemoveService>
	{
		@ApplicationScoped
		public static class RemoveComponentReadyEventDispatcher extends EventDispatcher<RemoveComponentReadyEvent>
		{
		}

		public RemoveComponentReadyEvent(final @NonNull Remove remove, final @NonNull RemoveService removeService) {
			super(remove, removeService);
		}

		/** programmatically specify command line vm option {@code --add-reads de.ruu.lib.fx.comp=ALL-UNNAMED} */
		public static void addReadsUnnamedModule()
		{
			RemoveComponentReadyEvent.class.getModule()
					.addReads(RemoveComponentReadyEvent.class.getClassLoader().getUnnamedModule());
		}
	}
}