package de.ruu.lib.fx.control.buttons;

import de.ruu.lib.cdi.common.CDIUtil;
import de.ruu.lib.fx.comp.FXCApp.FXStageShowingEvent;
import de.ruu.lib.fx.comp.FXCApp.FXStageShowingEvent.FXStageShowingEventDispatcher;
import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.control.buttons.RemoveService.RemoveComponentReadyEvent;
import de.ruu.lib.fx.control.buttons.RemoveService.RemoveComponentReadyEvent.RemoveComponentReadyEventDispatcher;
import javafx.stage.Stage;
import lombok.extern.slf4j.Slf4j;

import java.util.Optional;
import java.util.function.Consumer;

/**
 * Java FX Component Application Runner {@link RemoveAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.07.15 08:12:49:333
 */
@Slf4j class RemoveAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting {}", RemoveAppRunner.class.getName());

		RemoveComponentReadyEvent .addReadsUnnamedModule();
		FXCAppStartedEvent        .addReadsUnnamedModule();
		FXStageShowingEvent       .addReadsUnnamedModule();

		Runnable runBeforeAppLaunch =
				() ->
				{
					log.debug("starting runBeforeAppLaunch");
					log.debug("add new consumer to stage showing event dispatcher");
					// get application scoped event dispatcher from CDI and register a consumer
					FXStageShowingEventDispatcher fxStageShowingEventDispatcher =
							CDIUtil.select(FXStageShowingEventDispatcher.class);
					fxStageShowingEventDispatcher.add(new FXStageShowingEventConsumer());
					log.debug("add new consumer to remove component ready event dispatcher");
					// get application scoped event dispatcher from CDI and register a consumer
					RemoveComponentReadyEventDispatcher componentReadyEventDispatcher =
							CDIUtil.select(RemoveComponentReadyEventDispatcher.class);
					componentReadyEventDispatcher.add(new RemoveComponentReadyEventConsumer());
					log.debug(
							"\n" + "-".repeat(10) +
									"registered remove component ready consumer");
					log.debug("finished runBeforeAppLaunch");
				};

		FXCAppRunner.run(RemoveApp.class, args, runBeforeAppLaunch);

		log.debug("finished {}", RemoveAppRunner.class.getName());
	}

	private static class FXStageShowingEventConsumer implements Consumer<FXStageShowingEvent>
	{
		@Override public void accept(FXStageShowingEvent e)
		{
			log.debug(
					"\n" + "-".repeat(10) +
							"received stage showing event");
			Optional<Stage> stageOptional = e.data();
			stageOptional.ifPresent
					(
							stage ->
							{
								stage.setTitle("demo for add button");
								stage.setHeight(200);
								stage.setWidth (200);
//						stage.sizeToScene();
							}
					);
		}
	}

	private static class RemoveComponentReadyEventConsumer implements Consumer<RemoveComponentReadyEvent>
	{
		@Override public void accept(RemoveComponentReadyEvent e)
		{
			log.debug(
					"\n" + "-".repeat(10) +
							"received remove component ready event");
			e.service().button().setOnAction(btnClickedEvent -> log.info("remove button clicked: {}", btnClickedEvent));
		}
	}
}