package de.ruu.lib.jpa.core.mapstruct.demo.bidirectional;

import static java.util.Objects.isNull;

import java.util.HashSet;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

import de.ruu.lib.jpa.core.mapstruct.AbstractMappedDTO;
import de.ruu.lib.util.Strings;
import org.jspecify.annotations.NonNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DepartmentDTO extends AbstractMappedDTO<DepartmentEntity>
{
	private static final Logger log = LoggerFactory.getLogger(DepartmentDTO.class);

	/** mutable non-null */
	@NonNull private String name;

	/** mutable */
	private String description;

	/** no direct access to nullable modifiable set */
	private Set<EmployeeDTO> employees;

	protected DepartmentDTO() { }

	public DepartmentDTO(@NonNull String name)
	{
		Objects.requireNonNull(name, "name");
		name(name);
	}

	public String name()        { return name; }
	public String description() { return description; }

	public void description(String v) { this.description = v; }

	/** not generated by lombok because of extra parameter validation */
	public @NonNull DepartmentDTO name(@NonNull String name)
	{
		if (Strings.isEmptyOrBlank(name)) throw new IllegalArgumentException("name must not be empty nor blank");
		this.name = name;
		return this;
	}

	/** return optional unmodifiable */
	public Optional<Set<EmployeeDTO>> optionalEmployees()
	{
		if (isNull(employees)) return Optional.empty();
		return Optional.of(Set.copyOf(employees));
	}

	@Override public Long getId() { return super.getId(); }

	public boolean add(@NonNull EmployeeDTO employee)
	{
		if (employee.department() == this)
		{
			if (employeesContains(employee)) return true;
			return nonNullEmployees().add(employee);
		}
		else
		{
			// following check should never return true
			if (employeesContains(employee))
				log.error("employee with {} is already contained in {}", employee.department(), this);

			// assign this department as department of employee and update employees
			employee.department(this);
			return nonNullEmployees().add(employee);
		}
	}

	public boolean remove(@NonNull EmployeeDTO employee)
	{
		if (isNull(employees)) return false;
		return employees.remove(employee);
	}

	void beforeMapping(@NonNull DepartmentEntity input)
	{
		super.beforeMapping(input);
		if (input.optionalEmployees().isPresent())
				input.optionalEmployees().get().forEach(e -> add(e.toTarget()));
		name(input.name());
	}

	void afterMapping(@NonNull DepartmentEntity input)
	{
		super.afterMapping(input);
		log.debug("starting");
		log.debug("finished");
	}

	@Override public @NonNull DepartmentEntity toSource() { return Mapper.INSTANCE.map(this); }

	private Set<EmployeeDTO> nonNullEmployees()
	{
		if (isNull(employees)) employees = new HashSet<>();
		return employees;
	}

	private boolean employeesContains(EmployeeDTO employee)
	{
		if (isNull(employees)) return false;
		return employees.contains(employee);
	}

	@Override public boolean equals(Object o)
	{
		if (this == o) return true;
		if (!(o instanceof DepartmentDTO other)) return false;
		if (!super.equals(o)) return false;
		return Objects.equals(name, other.name) && Objects.equals(description, other.description);
	}

	@Override public int hashCode() { return Objects.hash(super.hashCode(), name, description); }

	@Override public String toString()
	{
		return super.toString() + ", DepartmentDTO(name=" + name + ", description=" + description + ")";
	}
}
