package de.ruu.lib.postgres.toolbox.ui;

import static de.ruu.lib.cdi.common.CDIUtil.fire;
import static de.ruu.lib.fx.FXUtil.stage;
import static de.ruu.lib.util.BooleanFunctions.not;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Optional;

import org.eclipse.microprofile.config.inject.ConfigProperty;

import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import de.ruu.lib.fx.control.dialog.AlertDialog;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.postgres.PostgresToolBox;
import de.ruu.lib.util.config.mp.ConfigSourceUtil;
import de.ruu.lib.util.config.mp.WritableFileConfigSource;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.DirectoryChooser;
import javafx.stage.FileChooser;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.12.21 09:57:08:116
 */
@Slf4j
@Dependent // Explicit: FXML controller lifecycle managed by FXMLLoader, not CDI
class PostgresBackupUIController extends DefaultFXCController<PostgresBackupUI, PostgresBackupUIService>
		implements PostgresBackupUIService
{
	public static final String POSTGRES_BACKUP_EXECUTABLE_KEY   = "postgres.backup.executable";
	public static final String POSTGRES_BACKUP_EXECUTABLE_VALUE = ".";
	public static final String POSTGRES_BACKUP_DIRECTORY_KEY    = "postgres.backup.directory";
	public static final String POSTGRES_BACKUP_DIRECTORY_VALUE  = ".";
	public static final String POSTGRES_BACKUP_FILENAME_KEY     = "postgres.backup.file";
	public static final String POSTGRES_BACKUP_FILENAME_VALUE   = ".";
	public static final String POSTGRES_BACKUP_HOST_KEY         = "postgres.backup.host";
	// public static final String POSTGRES_BACKUP_HOST_VALU E      = "localhost";
	public static final String POSTGRES_BACKUP_HOST_VALUE       = "172.26.187.214";
	public static final String POSTGRES_BACKUP_PORT_KEY         = "postgres.backup.port";
	public static final String POSTGRES_BACKUP_PORT_VALUE       = "5432";
	public static final String POSTGRES_BACKUP_DATABASE_KEY     = "postgres.backup.database";
	public static final String POSTGRES_BACKUP_DATABASE_VALUE   = "pragma";
	public static final String POSTGRES_BACKUP_USERNAME_KEY     = "postgres.backup.username";
	public static final String POSTGRES_BACKUP_USERNAME_VALUE   = "r_uu";
	public static final String POSTGRES_BACKUP_PASSWORD_KEY     = "postgres.backup.password";
	public static final String POSTGRES_BACKUP_PASSWORD_VALUE   = "change me";

	@FXML private Button btnExecute;

	@FXML private Button btnFileChooserExecutable;
	@FXML private Button btnBackupDirectoryChooser;

	@FXML private Button btnSaveSettings;

	@FXML private AnchorPane root;

	@FXML private TextField tfBackupExecutable;
	@FXML private TextField tfBackupDirectory;
	@FXML private TextField tfBackupFilename;
	@FXML private TextField tfDatabase;
	@FXML private TextField tfHost;
	@FXML private TextField pfPassword;
	@FXML private TextField tfPort;
	@FXML private TextField tfUsername;

	// cannot use @Observes(IF_EXISTS) directly because @Dependent beans don't support conditional observers
	@Inject private FXCAppStartedEvent.FXCAppStartedEventDispatcher appStartedEventDispatcher;

	// inject configuration values from file (initialized in AppRunner)
	@Inject @ConfigProperty(name = POSTGRES_BACKUP_EXECUTABLE_KEY, defaultValue = POSTGRES_BACKUP_EXECUTABLE_VALUE)
	private String postgresExecutable;
	@Inject @ConfigProperty(name = POSTGRES_BACKUP_DIRECTORY_KEY , defaultValue = POSTGRES_BACKUP_DIRECTORY_VALUE )
	private String postgresBackupDirectory;
	@Inject @ConfigProperty(name = POSTGRES_BACKUP_FILENAME_KEY  , defaultValue = POSTGRES_BACKUP_FILENAME_VALUE  )
	private String postgresBackupFilename;
	@Inject @ConfigProperty(name = POSTGRES_BACKUP_HOST_KEY      , defaultValue = POSTGRES_BACKUP_HOST_VALUE      )
	private String postgresHost;

	@Inject @ConfigProperty(name = POSTGRES_BACKUP_PORT_KEY      , defaultValue = POSTGRES_BACKUP_PORT_VALUE      )
	private String postgresPort;

	@Inject @ConfigProperty(name = POSTGRES_BACKUP_DATABASE_KEY  , defaultValue = POSTGRES_BACKUP_DATABASE_VALUE  )
	private String postgresDatabase;

	@Inject @ConfigProperty(name = POSTGRES_BACKUP_USERNAME_KEY  , defaultValue = POSTGRES_BACKUP_USERNAME_VALUE  )
	private String postgresUsername;

	@Inject @ConfigProperty(name = POSTGRES_BACKUP_PASSWORD_KEY  , defaultValue = POSTGRES_BACKUP_PASSWORD_VALUE  )
	private String postgresPassword;

	private WritableFileConfigSource configSource;

	@Override @FXML protected void initialize()
	{
		log.debug("initializing {}", getClass().getName());

		appStartedEventDispatcher.add(e -> onAppStarted(e));

		// get the WritableFileConfigSource (already initialized in AppRunner)
		Optional<WritableFileConfigSource> sourceOpt = ConfigSourceUtil.activeWritableFileConfigSource();
		if (sourceOpt.isPresent())
		{
			configSource = sourceOpt.get();
			log.info("using config: {}", configSource.getName());
		}
		else
		{
			log.warn("no WritableFileConfigSource found - using default values");
		}

		// Populate UI fields with injected values
		populateFields();

		btnFileChooserExecutable .setOnAction(event -> onBtnFileChooserExecutable ());
		btnBackupDirectoryChooser.setOnAction(event -> onBtnBackupDirectoryChooser());

		btnSaveSettings.setOnAction(event -> saveToConfig());
		btnExecute     .setOnAction(event -> onBtnExecute());

		// fire event to indicate that component is available
		// users of PostgresBackupUI should wait for this event to make sure that initialisation is completed before
		// accessing fields
		fire(new PostgresBackupUIReadyEvent(view(), this));
	}

	private void onAppStarted(FXCAppStartedEvent e)
	{
		stage(btnExecute).ifPresent(s -> s.setTitle("jeee RAAAH - postgres backup"));
	}

	private void onBtnFileChooserExecutable()
	{
		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("select backup executable");

		// use current value as starting point
		String currentPath = tfBackupExecutable.getText();
		if (currentPath != null && !currentPath.trim().isEmpty() && !currentPath.equals("."))
		{
			File currentFile = new File(currentPath);
			if (currentFile.exists())
			{
				if (currentFile.isFile())
				{
					fileChooser.setInitialDirectory(currentFile.getParentFile());
					fileChooser.setInitialFileName(currentFile.getName());
				}
				else if (currentFile.isDirectory())
				{
					fileChooser.setInitialDirectory(currentFile);
				}
			}
		}

		File selectedFile = fileChooser.showOpenDialog(root.getScene().getWindow());
		if (selectedFile != null)
		{
			tfBackupExecutable.setText(selectedFile.getAbsolutePath());
		}
	}

	private void onBtnBackupDirectoryChooser()
	{
		DirectoryChooser directoryChooser = new DirectoryChooser();
		directoryChooser.setTitle("select directory for backup file");

		// use current value as starting point
		String currentPath = tfBackupDirectory.getText();
		if (currentPath != null && !currentPath.trim().isEmpty() && !currentPath.equals("."))
		{
			File currentFile = new File(currentPath);
			if (currentFile.exists())
			{
				if (currentFile.isDirectory())
				{
					directoryChooser.setInitialDirectory(currentFile);
				}
			}
		}

		File selectedDirectory = directoryChooser.showDialog(root.getScene().getWindow());
		if (selectedDirectory != null)
		{
			tfBackupDirectory.setText(selectedDirectory.getAbsolutePath());
		}
	}

	private void onBtnExecute()
	{
		// Read current values from TextFields (not from injected config properties!)
		String executable      = tfBackupExecutable.getText();
		String backupDirectory = tfBackupDirectory.getText();
		String backupFileName  = tfBackupFilename .getText();
		String host            = tfHost           .getText();
		String port            = tfPort           .getText();
		String database        = tfDatabase       .getText();
		String username        = tfUsername       .getText();
		String password        = pfPassword       .getText();

		// Validate inputs before executing
		if (not(validateInputs(executable, backupFileName, host, port, database, username)))
		{
			return;
		}

		try
		{
			PostgresToolBox
					.backup
					(
						Path.of(executable),
						host,
						Integer.parseInt(port),
						database,
						username,
						password,
						Path.of(backupDirectory, backupFileName)
					);
			AlertDialog
					.showAndWait
					(
						"success",
						"backup complete",
						"database: " + database,
						Alert.AlertType.INFORMATION
					);
		}
		catch (IOException | InterruptedException e)
		{
			ExceptionDialog.showAndWait("failure executing backup", e);
		}
	}

	/**
	 * Validates all input fields before executing backup.
	 * Shows error dialog if validation fails.
	 * @param executable path to pg_dump executable
	 * @param targetFile path to target backup file
	 * @param host database host
	 * @param port database port
	 * @param database database name
	 * @param username database username
	 * @return true if all inputs are valid, false otherwise
	 */
	private boolean validateInputs(String executable, String targetFile, String host, String port, String database, String username)
	{
		// Check if executable path is set and valid
		if (executable == null || executable.trim().isEmpty() || executable.equals("."))
		{
			AlertDialog.showAndWait(
				"Invalid Configuration",
				"Please select a valid pg_dump executable.",
				"Current value: '" + executable + "' is not a valid executable path.\n\n" +
				"Click the folder icon next to 'Executable' to select pg_dump or pg_dump.exe",
				Alert.AlertType.ERROR
			);
			return false;
		}

		File executableFile = new File(executable);
		if (!executableFile.exists())
		{
			AlertDialog.showAndWait(
				"Executable Not Found",
				"The pg_dump executable does not exist.",
				"Path: " + executable + "\n\n" +
				"Please verify the path and select a valid pg_dump executable.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		if (!executableFile.canExecute())
		{
			AlertDialog.showAndWait(
				"No Execute Permission",
				"The selected file is not executable.",
				"Path: " + executable + "\n\n" +
				"Please select the pg_dump executable file (not a directory).",
				Alert.AlertType.ERROR
			);
			return false;
		}

		// Check if target file path is set and valid
		if (targetFile == null || targetFile.trim().isEmpty() || targetFile.equals("."))
		{
			AlertDialog.showAndWait(
				"Invalid Target File",
				"Please select a valid target file for the backup.",
				"Current value: '" + targetFile + "' is not a valid file path.\n\n" +
				"Click the folder icon next to 'Target File' to select a location.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		// Check required database connection parameters
		if (host == null || host.trim().isEmpty())
		{
			AlertDialog.showAndWait(
				"Missing Host",
				"",
				"Please enter the PostgreSQL host address.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		if (database == null || database.trim().isEmpty())
		{
			AlertDialog.showAndWait(
				"Missing Database Name",
				"",
				"Please enter the database name to backup.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		if (username == null || username.trim().isEmpty())
		{
			AlertDialog.showAndWait(
				"Missing Username",
				"",
				"Please enter the PostgreSQL username.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		// Validate port number
		try
		{
			int portNum = Integer.parseInt(port);
			if (portNum < 1 || portNum > 65535)
			{
				AlertDialog.showAndWait(
					"Invalid Port",
					"Port must be between 1 and 65535.",
					"Current value: " + port,
					Alert.AlertType.ERROR
				);
				return false;
			}
		}
		catch (NumberFormatException e)
		{
			AlertDialog.showAndWait(
				"Invalid Port",
				"Port must be a valid number.",
				"Current value: " + port,
				Alert.AlertType.ERROR
			);
			return false;
		}

		return true;
	}

	/** Populates the UI fields with the values from the config file */
	private void populateFields()
	{
		// Populate backup fields
		tfBackupExecutable.setText(postgresExecutable     );
		tfBackupDirectory.setText(postgresBackupDirectory);
//		tfBackupFilename .setText(postgresBackupFilename );
		tfHost           .setText(postgresHost           );
		tfPort           .setText(postgresPort           );
		tfDatabase       .setText(postgresDatabase       );
		tfUsername       .setText(postgresUsername       );
		pfPassword       .setText(postgresPassword       );

		// Create timestamp in format yyyy.MM.dd-HH.mm
		LocalDateTime     now       = LocalDateTime.now();
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy.MM.dd-HH.mm");
		String            timestamp = now.format(formatter);

		// Construct postgresBackupFilename: yyyy.MM.dd-HH.mm-text.pg-dump
		String postgresBackupFilename = timestamp + "-text.pg-dump";

		tfBackupFilename .setText(postgresBackupFilename);
	}

	/** Save current field values back to config file */
	private void saveToConfig()
	{
		log.debug("saving configuration to file");
		if (configSource != null)
		{
			log.debug("saving configuration to file {}", configSource.getName());

			configSource.setProperty(POSTGRES_BACKUP_EXECUTABLE_KEY, tfBackupExecutable.getText());
			configSource.setProperty(POSTGRES_BACKUP_DIRECTORY_KEY , tfBackupDirectory.getText());
			configSource.setProperty(POSTGRES_BACKUP_HOST_KEY      , tfHost           .getText());
			configSource.setProperty(POSTGRES_BACKUP_PORT_KEY      , tfPort           .getText());
			configSource.setProperty(POSTGRES_BACKUP_DATABASE_KEY  , tfDatabase       .getText());
			configSource.setProperty(POSTGRES_BACKUP_USERNAME_KEY  , tfUsername       .getText());
			configSource.setProperty(POSTGRES_BACKUP_PASSWORD_KEY  , pfPassword       .getText());

			log.info("configuration saved to file {}", configSource.getName());
		}
	}
}
