package de.ruu.lib.postgres.toolbox.ui;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.postgres.PostgresToolBox;
import de.ruu.lib.postgres.toolbox.ui.PostgresRestoreUIService.PostgresRestoreUIReadyEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link PostgresUtilUIAppRunner}
 * <p>
 * Generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.12.21 09:57:08:129
 * <p>
 * JPMS Module Access: This runner must call {@code FXCAppRunner.configureModuleAccessForCDI()} before launching the
 * application to configure JPMS module read access for Weld CDI. Application-specific CDI events requiring module
 * access should be registered after configureModuleAccessForCDI() and before {@code FXCAppRunner.run()}.
 */
@Slf4j
class PostgresRestoreUIAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting {}", PostgresRestoreUIAppRunner.class.getName());

		// Initialize config file with defaults BEFORE CDI starts
		PostgresToolBox.initializePostgresUtilConfig();

		// configure jpms module access for cdi
		FXCAppRunner.configureModuleAccessForCDI(); // configure for fxc framework events
		PostgresRestoreUIReadyEvent.addReadsUnnamedModule(); // configure for this component's events

		FXCAppRunner.run(PostgresRestoreUIApp.class, args);

		log.debug("finished {}", PostgresRestoreUIAppRunner.class.getName());
	}
}
