package de.ruu.lib.postgres.toolbox.ui;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link PostgresUtilUI}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.12.21 09:57:08:095
 */
public class PostgresUtilUI
		extends DefaultFXCView<PostgresUtilUI, PostgresUtilUIService, PostgresUtilUIController>
		implements PostgresUtilUIService
{
}
