package de.ruu.lib.postgres.toolbox.ui;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link PostgresUtilUIApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.12.21 09:57:08:127
 */
public class PostgresBackupUIApp extends FXCApp { }
