package de.ruu.lib.postgres.toolbox.ui;

import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.comp.FXCService;
import de.ruu.lib.util.AbstractEvent;
import jakarta.enterprise.context.ApplicationScoped;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.12.21 09:57:08:113
 */
public interface PostgresRestoreUIService extends FXCService
{
	/** Event that is fired to indicate that a {@link PostgresBackupUI} component has become available. */
	class PostgresRestoreUIReadyEvent extends AbstractEvent<PostgresRestoreUI, PostgresRestoreUIService>
	{
		public PostgresRestoreUIReadyEvent(final PostgresRestoreUI component, final PostgresRestoreUIService service)
		{
			super(component, service);
		}

		/** programmatically specify command line vm option {@code --add-reads de.ruu.lib.fx.comp=ALL-UNNAMED} */
		public static void addReadsUnnamedModule()
		{
			PostgresRestoreUIReadyEvent.class.getModule()
					.addReads(PostgresRestoreUIReadyEvent.class.getClassLoader().getUnnamedModule());
		}

		@ApplicationScoped
		public static class PostgresRestoreUIReadyEventDispatcher extends EventDispatcher<PostgresRestoreUIReadyEvent>
		{
		}
	}
}
