package de.ruu.lib.postgres.toolbox.ui;

import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import de.ruu.lib.fx.control.dialog.AlertDialog;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.postgres.PostgresToolBox;
import de.ruu.lib.util.config.mp.ConfigSourceUtil;
import de.ruu.lib.util.config.mp.WritableFileConfigSource;
import jakarta.inject.Inject;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.DirectoryChooser;
import javafx.stage.FileChooser;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Optional;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.12.21 09:57:08:116
 */
class PostgresUtilUIController extends DefaultFXCController<PostgresUtilUI, PostgresUtilUIService>
		implements PostgresUtilUIService
{
	private static final Logger log = LoggerFactory.getLogger(PostgresUtilUIController.class);

	public static final String POSTGRES_BACKUP_EXE_KEY         = "postgres.backup.exe";
	public static final String POSTGRES_BACKUP_EXE_VALUE       = ".";
	public static final String POSTGRES_BACKUP_FILE_KEY        = "postgres.backup.file";
	public static final String POSTGRES_BACKUP_FILE_VALUE      = ".";
	public static final String POSTGRES_BACKUP_HOST_KEY        = "postgres.backup.host";
// public static final String POSTGRES_BACKUP_HOST_VALUE       = "localhost";
	public static final String POSTGRES_BACKUP_HOST_VALUE      = "172.26.187.214";
	public static final String POSTGRES_BACKUP_PORT_KEY        = "postgres.backup.port";
	public static final String POSTGRES_BACKUP_PORT_VALUE      = "5432";
	public static final String POSTGRES_BACKUP_DATABASE_KEY    = "postgres.backup.database";
	public static final String POSTGRES_BACKUP_DATABASE_VALUE  = "pragma";
	public static final String POSTGRES_BACKUP_USERNAME_KEY    = "postgres.backup.username";
	public static final String POSTGRES_BACKUP_USERNAME_VALUE  = "r_uu";
	public static final String POSTGRES_BACKUP_PASSWORD_KEY    = "postgres.backup.password";
	public static final String POSTGRES_BACKUP_PASSWORD_VALUE  = "change me";

	public static final String POSTGRES_RESTORE_EXE_KEY        = "postgres.restore.exe";
	public static final String POSTGRES_RESTORE_EXE_VALUE      = ".";
	public static final String POSTGRES_RESTORE_FILE_KEY       = "postgres.restore.file";
	public static final String POSTGRES_RESTORE_FILE_VALUE     = POSTGRES_BACKUP_FILE_VALUE;
	public static final String POSTGRES_RESTORE_HOST_KEY       = "postgres.restore.host";
// public static final String POSTGRES_RESTORE_HOST_VALUE      = "localhost";
	public static final String POSTGRES_RESTORE_HOST_VALUE     = POSTGRES_BACKUP_HOST_VALUE;
	public static final String POSTGRES_RESTORE_PORT_KEY       = "postgres.restore.port";
	public static final String POSTGRES_RESTORE_PORT_VALUE     = POSTGRES_BACKUP_PORT_VALUE;
	public static final String POSTGRES_RESTORE_DATABASE_KEY   = "postgres.restore.database";
	public static final String POSTGRES_RESTORE_DATABASE_VALUE = POSTGRES_BACKUP_DATABASE_VALUE;
	public static final String POSTGRES_RESTORE_USERNAME_KEY   = "postgres.restore.username";
	public static final String POSTGRES_RESTORE_USERNAME_VALUE = POSTGRES_BACKUP_USERNAME_VALUE;
	public static final String POSTGRES_RESTORE_PASSWORD_KEY   = "postgres.restore.password";
	public static final String POSTGRES_RESTORE_PASSWORD_VALUE = POSTGRES_BACKUP_PASSWORD_VALUE;

	@FXML private Button btnExecuteBackup;
	@FXML private Button btnExecuteRestore;

	@FXML private Button btnFileChooserExecutableBackup;
	@FXML private Button btnFileChooserExecutableRestore;
	@FXML private Button btnFileChooserTarget;
	@FXML private Button btnFileChooserSource;

	@FXML private Button btnSaveSettings;

	@FXML private AnchorPane root;

	@FXML private TextField tfExecutableBackup;
	@FXML private TextField tfExecutableRestore;
	@FXML private TextField tfTargetFile;
	@FXML private TextField tfSourceFile;
	@FXML private TextField tfDatabaseBackup;
	@FXML private TextField tfDatabaseRestore;
	@FXML private TextField tfHostBackup;
	@FXML private TextField tfHostRestore;
	@FXML private TextField tfPasswordBackup;
	@FXML private TextField tfPasswordRestore;
	@FXML private TextField tfPortBackup;
	@FXML private TextField tfPortRestore;
	@FXML private TextField tfUsernameBackup;
	@FXML private TextField tfUsernameRestore;

	// Inject configuration values from file (initialized in AppRunner)
	@Inject @ConfigProperty(name = POSTGRES_BACKUP_EXE_KEY      , defaultValue = POSTGRES_BACKUP_EXE_VALUE      )
	private String postgresExeBackup;
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_EXE_KEY     , defaultValue = POSTGRES_RESTORE_EXE_VALUE     )
	private String postgresExeRestore;
	@Inject @ConfigProperty(name = POSTGRES_BACKUP_FILE_KEY     , defaultValue = POSTGRES_BACKUP_FILE_VALUE     )
	private String postgresFileBackup;
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_FILE_KEY    , defaultValue = POSTGRES_RESTORE_FILE_VALUE    )
	private String postgresFileRestore;
	@Inject @ConfigProperty(name = POSTGRES_BACKUP_HOST_KEY     , defaultValue = POSTGRES_BACKUP_HOST_VALUE     )
	private String postgresHostBackup;
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_HOST_KEY    , defaultValue = POSTGRES_RESTORE_HOST_VALUE    )
	private String postgresHostRestore;

	@Inject @ConfigProperty(name = POSTGRES_BACKUP_PORT_KEY     , defaultValue = POSTGRES_BACKUP_PORT_VALUE     )
	private String postgresPortBackup;
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_PORT_KEY    , defaultValue = POSTGRES_RESTORE_PORT_VALUE    )
	private String postgresPortRestore;

	@Inject @ConfigProperty(name = POSTGRES_BACKUP_DATABASE_KEY , defaultValue = POSTGRES_BACKUP_DATABASE_VALUE )
	private String postgresDatabaseBackup;
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_DATABASE_KEY, defaultValue = POSTGRES_RESTORE_DATABASE_VALUE)
	private String postgresDatabaseRestore;

	@Inject @ConfigProperty(name = POSTGRES_BACKUP_USERNAME_KEY , defaultValue = POSTGRES_BACKUP_USERNAME_VALUE )
	private String postgresUsernameBackup;
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_USERNAME_KEY, defaultValue = POSTGRES_RESTORE_USERNAME_VALUE)
	private String postgresUsernameRestore;

	@Inject @ConfigProperty(name = POSTGRES_BACKUP_PASSWORD_KEY , defaultValue = POSTGRES_BACKUP_PASSWORD_VALUE )
	private String postgresPasswordBackup;
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_PASSWORD_KEY, defaultValue = POSTGRES_RESTORE_PASSWORD_VALUE)
	private String postgresPasswordRestore;

	private WritableFileConfigSource configSource;

	@Override @FXML
	protected void initialize()
	{
		log.debug("initializing {}", getClass().getName());

		// get the WritableFileConfigSource (already initialized in AppRunner)
		Optional<WritableFileConfigSource> sourceOpt = ConfigSourceUtil.activeWritableFileConfigSource();
		if (sourceOpt.isPresent())
		{
			configSource = sourceOpt.get();
			log.info("using config: {}", configSource.getName());
		}
		else
		{
			log.warn("no WritableFileConfigSource found - using default values");
		}

		// Populate UI fields with injected values
		populateFields();

		btnFileChooserExecutableBackup .setOnAction(event -> onBtnFileChooserExecutableBackup ());
		btnFileChooserExecutableRestore.setOnAction(event -> onBtnFileChooserExecutableRestore());
		btnFileChooserTarget           .setOnAction(event -> onBtnFileChooserTarget           ());

		btnSaveSettings  .setOnAction(event -> saveToConfig       ());
		btnExecuteBackup .setOnAction(event -> onBtnExecuteBackup ());
		btnExecuteRestore.setOnAction(event -> onBtnExecuteRestore());
	}

	private void onBtnFileChooserExecutableBackup()
	{
		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("select backup executable");
		File selectedFile = fileChooser.showOpenDialog(root.getScene().getWindow());
		if (selectedFile != null)
		{
			tfExecutableBackup.setText(selectedFile.getAbsolutePath());
		}
	}

	private void onBtnFileChooserExecutableRestore()
	{
		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("select restore executable");
		File selectedFile = fileChooser.showOpenDialog(root.getScene().getWindow());
		if (selectedFile != null)
		{
			tfExecutableRestore.setText(selectedFile.getAbsolutePath());
		}
	}

	private void onBtnFileChooserTarget()
	{
		DirectoryChooser directoryChooser = new DirectoryChooser();
		directoryChooser.setTitle("select target directory");
		File selectedDirectory = directoryChooser.showDialog(root.getScene().getWindow());
		if (selectedDirectory != null)
		{
			// Create timestamp in format yyyy.MM.dd-HH.mm
			LocalDateTime now = LocalDateTime.now();
			DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy.MM.dd-HH.mm");
			String timestamp = now.format(formatter);

			// Construct filename: yyyy.MM.dd-HH.mm-text.pg-dump
			String filename = timestamp + "-text.pg-dump";

			// Combine directory and filename
			File targetFile = new File(selectedDirectory, filename);
			tfTargetFile.setText(targetFile.getAbsolutePath());
		}
	}

	private void onBtnExecuteBackup()
	{
		try
		{
			PostgresToolBox
					.backup
					(
						Path.of(postgresExeBackup),
						postgresHostBackup,
						Integer.parseInt(postgresPortBackup),
						postgresDatabaseBackup,
						postgresUsernameBackup,
						postgresPasswordBackup,
						Path.of(postgresFileBackup)
					);
			AlertDialog
					.showAndWait
					(
						"success",
						"backup complete",
						"database: " + postgresDatabaseBackup,
						Alert.AlertType.INFORMATION
					);
		}
		catch (IOException | InterruptedException e)
		{
			ExceptionDialog.showAndWait("failure executing backup", e);
		}
	}

	private void onBtnExecuteRestore()
	{
		try
		{
			PostgresToolBox
					.restore
					(
							Path.of(tfExecutableRestore.getText()),
							tfHostRestore.getText(),
							Integer.parseInt(tfPortRestore.getText()),
							tfDatabaseRestore.getText(),
							tfUsernameRestore.getText(),
							tfPasswordRestore.getText(),
							Path.of(tfSourceFile.getText())
					);
			AlertDialog
					.showAndWait
						(
							"success",
							"restore complete",
							"database: " + tfDatabaseRestore.getText(),
							Alert.AlertType.INFORMATION
						);
		}
		catch (IOException | InterruptedException e)
		{
			ExceptionDialog.showAndWait("failure executing restore", e);
		}
	}

	/** Populates the UI fields with the values from the config file */
	private void populateFields()
	{
		// Populate backup fields
		tfExecutableBackup .setText(postgresExeBackup      );
		tfSourceFile       .setText(postgresFileBackup     );
		tfHostBackup       .setText(postgresHostBackup     );
		tfPortBackup       .setText(postgresPortBackup     );
		tfDatabaseBackup   .setText(postgresDatabaseBackup );
		tfUsernameBackup   .setText(postgresUsernameBackup );
		tfPasswordBackup   .setText(postgresPasswordBackup );

		// Populate restore fields (same values initially)
		tfExecutableRestore.setText(postgresExeRestore     );
		tfTargetFile       .setText(postgresFileRestore    );
		tfHostRestore      .setText(postgresHostRestore    );
		tfPortRestore      .setText(postgresPortRestore    );
		tfDatabaseRestore  .setText(postgresDatabaseRestore);
		tfUsernameRestore  .setText(postgresUsernameRestore);
		tfPasswordRestore  .setText(postgresPasswordRestore);
	}

	/** Save current field values back to config file */
	private void saveToConfig()
	{
		log.debug("saving configuration to file");
		if (configSource != null)
		{
			log.debug("saving configuration to file {}", configSource.getName());

			String targetFileAsString = tfTargetFile.getText();
			String sourceFileAsString = tfSourceFile.getText();

			if (targetFileAsString.isBlank() || sourceFileAsString.isBlank())
			{
				targetFileAsString = ".";
				sourceFileAsString = ".";
			}

			String targetFileDirectory = targetFileAsString.substring(0, targetFileAsString.lastIndexOf(File.separator));
			String sourceFileDirectory = sourceFileAsString.substring(0, sourceFileAsString.lastIndexOf(File.separator));

			configSource.setProperty(POSTGRES_BACKUP_FILE_KEY     , targetFileDirectory          );
			configSource.setProperty(POSTGRES_RESTORE_FILE_KEY    , sourceFileDirectory          );

			configSource.setProperty(POSTGRES_BACKUP_EXE_KEY      , tfExecutableBackup .getText());
			configSource.setProperty(POSTGRES_BACKUP_HOST_KEY     , tfHostBackup       .getText());
			configSource.setProperty(POSTGRES_BACKUP_PORT_KEY     , tfPortBackup       .getText());
			configSource.setProperty(POSTGRES_BACKUP_DATABASE_KEY , tfDatabaseBackup   .getText());
			configSource.setProperty(POSTGRES_BACKUP_USERNAME_KEY , tfUsernameBackup   .getText());
			configSource.setProperty(POSTGRES_BACKUP_PASSWORD_KEY , tfPasswordBackup   .getText());

			configSource.setProperty(POSTGRES_RESTORE_EXE_KEY     , tfExecutableRestore.getText());
			configSource.setProperty(POSTGRES_RESTORE_HOST_KEY    , tfHostRestore      .getText());
			configSource.setProperty(POSTGRES_RESTORE_PORT_KEY    , tfPortRestore      .getText());
			configSource.setProperty(POSTGRES_RESTORE_DATABASE_KEY, tfDatabaseRestore  .getText());
			configSource.setProperty(POSTGRES_RESTORE_USERNAME_KEY, tfUsernameRestore  .getText());
			configSource.setProperty(POSTGRES_RESTORE_PASSWORD_KEY, tfPasswordRestore  .getText());

			log.info("configuration saved to file {}", configSource.getName());
		}
	}
}
