package de.ruu.lib.fx.comp.demo.hierarchy;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.05.17 12:57:18:186
 */
public interface HierarchyDemoMainService extends FXCService { }