package de.ruu.lib.fx.comp.demo.hierarchy;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link HierarchyDemoMain}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.05.17 12:57:18:175
 */
public class HierarchyDemoMain extends DefaultFXCView<HierarchyDemoMain, HierarchyDemoMainService, HierarchyDemoMainController> { }