package de.ruu.lib.fx.comp.demo.hierarchy;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link HierarchyDemoMainApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.05.17 12:57:18:200
 */
public class HierarchyDemoMainApp extends FXCApp
{
}