#Writable config
#Tue Mar 31 21:35:26 CEST 2026
postgres.connection.timeout=30000
postgres.database=mydb
postgres.host=localhost
postgres.max.pool.size=10
postgres.password=changeme
postgres.port=5432
postgres.schema=public
postgres.ssl.enabled=false
postgres.username=admin
