package de.ruu.lib.fx.demo.comp.main;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link RUUFXDemoComponentMainApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.05.20 14:28:47:959
 */
public class RUUFXDemoComponentMainApp extends FXCApp
{
}