package de.ruu.lib.fx.demo.comp.main;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.05.20 14:28:47:939
 */
public interface RUUFXDemoComponentMainService extends FXCService	{ }