package de.ruu.lib.fx.comp.demo.hierarchy.sub1;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link HierarchyDemoSub1App}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.05.17 12:57:18:217
 */
public class HierarchyDemoSub1App extends FXCApp
{
}