package de.ruu.lib.fx.comp.demo.hierarchy.sub1;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link HierarchyDemoSub1}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.05.17 12:57:18:212
 */
public class HierarchyDemoSub1 extends DefaultFXCView<HierarchyDemoSub1, HierarchyDemoSub1Service, HierarchyDemoSub1Controller>
{
}