package de.ruu.lib.fx.comp.demo.hierarchy.sub1;

import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.05.17 12:57:18:214
 */
public class HierarchyDemoSub1Controller extends DefaultFXCController<HierarchyDemoSub1, HierarchyDemoSub1Service>
{
	@Override protected void initialize() { }
}