package de.ruu.lib.postgres.toolbox.ui;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.postgres.PostgresToolBox;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link PostgresUtilUIAppRunner}
 * <p>
 * Generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.12.21 09:57:08:129
 * <p>
 * JPMS Module Access: This runner must call {@code FXCAppRunner.configureModuleAccessForCDI()} before launching the
 * application to configure JPMS module read access for Weld CDI. Application-specific CDI events requiring module
 * access should be registered after configureModuleAccessForCDI() and before {@code FXCAppRunner.run()}.
 */
@Slf4j
public class PostgresUtilUIAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting {}", PostgresUtilUIAppRunner.class.getName());

		// Initialize config file with defaults BEFORE CDI starts
		PostgresToolBox.initializePostgresUtilConfig();

		// Configure JPMS module access for Weld CDI
		FXCAppRunner.configureModuleAccessForCDI();
		FXCAppRunner.run(PostgresUtilUIApp.class, args);

		log.debug("finished {}", PostgresUtilUIAppRunner.class.getName());
	}
}