package de.ruu.lib.postgres.toolbox.ui;

import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import de.ruu.lib.fx.control.dialog.AlertDialog;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.postgres.PostgresToolBox;
import de.ruu.lib.util.config.mp.ConfigSourceUtil;
import de.ruu.lib.util.config.mp.WritableFileConfigSource;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.FileChooser;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Optional;

import static de.ruu.lib.cdi.common.CDIUtil.fire;
import static de.ruu.lib.fx.FXUtil.getStage;
import static de.ruu.lib.util.BooleanFunctions.not;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.12.21 09:57:08:116
 */
@Slf4j
@Dependent // Explicit: FXML controller lifecycle managed by FXMLLoader, not CDI
class PostgresRestoreUIController extends DefaultFXCController<PostgresRestoreUI, PostgresRestoreUIService>
		implements PostgresRestoreUIService
{
	public static final String POSTGRES_RESTORE_EXECUTABLE_KEY   = "postgres.restore.executable";
	public static final String POSTGRES_RESTORE_EXECUTABLE_VALUE = ".";
	public static final String POSTGRES_RESTORE_FILE_KEY         = "postgres.restore.file";
	public static final String POSTGRES_RESTORE_FILE_VALUE       = ".";
	public static final String POSTGRES_RESTORE_HOST_KEY         = "postgres.restore.host";
	// public static final String POSTGRES_RESTORE_HOST_VALUE       = "localhost";
	public static final String POSTGRES_RESTORE_HOST_VALUE       = "172.26.187.214";
	public static final String POSTGRES_RESTORE_PORT_KEY         = "postgres.restore.port";
	public static final String POSTGRES_RESTORE_PORT_VALUE       = "5432";
	public static final String POSTGRES_RESTORE_DATABASE_KEY     = "postgres.restore.database";
	public static final String POSTGRES_RESTORE_DATABASE_VALUE   = "jeeeraaah";
	public static final String POSTGRES_RESTORE_USERNAME_KEY     = "postgres.restore.username";
	public static final String POSTGRES_RESTORE_USERNAME_VALUE   = "r_uu";
	public static final String POSTGRES_RESTORE_PASSWORD_KEY     = "postgres.restore.password";
	public static final String POSTGRES_RESTORE_PASSWORD_VALUE   = "change me";

	@FXML private Button btnExecute;

	@FXML private Button btnRestoreExecutableFileChooser;
	@FXML private Button btnBackupFileChooser;

	@FXML private Button btnSaveSettings;

	@FXML private AnchorPane root;

	@FXML private TextField tfRestoreExecutable;
	@FXML private TextField tfBackupFile;
	@FXML private TextField tfDatabase;
	@FXML private TextField tfHost;
	@FXML private TextField pfPassword;
	@FXML private TextField tfPort;
	@FXML private TextField tfUsername;

	// cannot use @Observes(IF_EXISTS) directly because @Dependent beans don't support conditional observers
	@Inject private FXCAppStartedEvent.FXCAppStartedEventDispatcher appStartedEventDispatcher;

	// inject configuration values from file (initialized in AppRunner)
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_EXECUTABLE_KEY, defaultValue = POSTGRES_RESTORE_EXECUTABLE_VALUE)
	private String postgresExecutable;
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_FILE_KEY      , defaultValue = POSTGRES_RESTORE_FILE_VALUE      )
	private String postgresSourceFile;
	@Inject @ConfigProperty(name = POSTGRES_RESTORE_HOST_KEY      , defaultValue = POSTGRES_RESTORE_HOST_VALUE      )
	private String postgresHost;

	@Inject @ConfigProperty(name = POSTGRES_RESTORE_PORT_KEY      , defaultValue = POSTGRES_RESTORE_PORT_VALUE      )
	private String postgresPort;

	@Inject @ConfigProperty(name = POSTGRES_RESTORE_DATABASE_KEY  , defaultValue = POSTGRES_RESTORE_DATABASE_VALUE  )
	private String postgresDatabase;

	@Inject @ConfigProperty(name = POSTGRES_RESTORE_USERNAME_KEY  , defaultValue = POSTGRES_RESTORE_USERNAME_VALUE  )
	private String postgresUsername;

	@Inject @ConfigProperty(name = POSTGRES_RESTORE_PASSWORD_KEY  , defaultValue = POSTGRES_RESTORE_PASSWORD_VALUE  )
	private String postgresPassword;

	private WritableFileConfigSource configSource;

	@Override @FXML protected void initialize()
	{
		log.debug("initializing {}", getClass().getName());

		appStartedEventDispatcher.add(e -> onAppStarted(e));

		log.debug("initializing {}", getClass().getName());

		// get the WritableFileConfigSource (already initialized in AppRunner)
		Optional<WritableFileConfigSource> sourceOpt = ConfigSourceUtil.activeWritableFileConfigSource();
		if (sourceOpt.isPresent())
		{
			configSource = sourceOpt.get();
			log.info("using config: {}", configSource.getName());
		}
		else
		{
			log.warn("no WritableFileConfigSource found - using default values");
		}

		// Populate UI fields with injected values
		populateFields();

		btnRestoreExecutableFileChooser.setOnAction(event -> onBtnFileChooserExecutable());
		btnBackupFileChooser           .setOnAction(event -> onBtnBackupFileChooser());

		btnSaveSettings.setOnAction(event -> saveToConfig());
		btnExecute     .setOnAction(event -> onBtnExecute());

		// fire event to indicate that component is available
		// users of PostgresRestoreUI should wait for this event to make sure that initialisation is completed before
		// accessing fields
		fire(new PostgresRestoreUIReadyEvent(view(), this));
	}

	private void onAppStarted(FXCAppStartedEvent e)
	{
		getStage(btnExecute).ifPresent(s -> s.setTitle("jeee RAAAH - postgres restore"));
	}

	private void onBtnFileChooserExecutable()
	{
		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("select restore executable");

		// use current value as starting point
		String currentPath = tfRestoreExecutable.getText();
		if (currentPath != null && !currentPath.trim().isEmpty() && !currentPath.equals("."))
		{
			File currentFile = new File(currentPath);
			if (currentFile.exists())
			{
				if (currentFile.isFile())
				{
					fileChooser.setInitialDirectory(currentFile.getParentFile());
					fileChooser.setInitialFileName(currentFile.getName());
				}
				else if (currentFile.isDirectory())
				{
					fileChooser.setInitialDirectory(currentFile);
				}
			}
		}

		File selectedFile = fileChooser.showOpenDialog(root.getScene().getWindow());
		if (selectedFile != null)
		{
			tfRestoreExecutable.setText(selectedFile.getAbsolutePath());
		}
	}

	private void onBtnBackupFileChooser()
	{
		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("select backup file to restore");

		// use current value as starting point
		String currentPath = tfBackupFile.getText();
		if (currentPath != null && !currentPath.trim().isEmpty() && !currentPath.equals("."))
		{
			File currentFile = new File(currentPath);
			if (currentFile.exists())
			{
				if (currentFile.isDirectory())
				{
					fileChooser.setInitialDirectory(currentFile);
				}
				else if (currentFile.isFile())
				{
					fileChooser.setInitialDirectory(currentFile.getParentFile());
					fileChooser.setInitialFileName(currentFile.getName());
				}
			}
		}

		File selectedFile = fileChooser.showOpenDialog(root.getScene().getWindow());
		if (selectedFile != null)
		{
			tfBackupFile.setText(selectedFile.getAbsolutePath());
		}
	}

	private void onBtnExecute()
	{
		// Read current values from TextFields (not from injected config properties!)
		String executable = tfRestoreExecutable.getText();
		String sourceFile = tfBackupFile       .getText();
		String host       = tfHost             .getText();
		String port       = tfPort             .getText();
		String database   = tfDatabase         .getText();
		String username   = tfUsername         .getText();
		String password   = pfPassword         .getText();

		// Validate inputs before executing
		if (not(validateInputs(executable, sourceFile, host, port, database, username)))
		{
			return;
		}

		try
		{
			PostgresToolBox
					.restore
					(
							Path.of(executable),
							host,
							Integer.parseInt(port),
							database,
							username,
							password,
							Path.of(sourceFile)
					);
			AlertDialog
					.showAndWait
						(
							"success",
							"restore complete",
							"database: " + database,
							Alert.AlertType.INFORMATION
						);
		}
		catch (IOException | InterruptedException e)
		{
			ExceptionDialog.showAndWait("failure executing restore", e);
		}
	}

	/**
	 * Validates all input fields before executing restore.
	 * Shows error dialog if validation fails.
	 * @param executable path to pg_restore executable
	 * @param sourceFile path to source backup file
	 * @param host database host
	 * @param port database port
	 * @param database database name
	 * @param username database username
	 * @return true if all inputs are valid, false otherwise
	 */
	private boolean validateInputs(String executable, String sourceFile, String host, String port, String database, String username)
	{
		// Check if executable path is set and valid
		if (executable == null || executable.trim().isEmpty() || executable.equals("."))
		{
			AlertDialog.showAndWait(
				"Invalid Configuration",
				"Please select a valid pg_restore executable.",
				"Current value: '" + executable + "' is not a valid executable path.\n\n" +
				"Click the folder icon next to 'Executable' to select pg_restore or pg_restore.exe",
				Alert.AlertType.ERROR
			);
			return false;
		}

		File executableFile = new File(executable);
		if (!executableFile.exists())
		{
			AlertDialog.showAndWait(
				"Executable Not Found",
				"The pg_restore executable does not exist.",
				"Path: " + executable + "\n\n" +
				"Please verify the path and select a valid pg_restore executable.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		if (!executableFile.canExecute())
		{
			AlertDialog.showAndWait(
				"No Execute Permission",
				"The selected file is not executable.",
				"Path: " + executable + "\n\n" +
				"Please select the pg_restore executable file (not a directory).",
				Alert.AlertType.ERROR
			);
			return false;
		}

		// Check if source file path is set and valid
		if (sourceFile == null || sourceFile.trim().isEmpty() || sourceFile.equals("."))
		{
			AlertDialog.showAndWait(
				"Invalid Source File",
				"Please select a valid backup file to restore.",
				"Current value: '" + sourceFile + "' is not a valid file path.\n\n" +
				"Click the folder icon next to 'Source File' to select a backup file.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		File source = new File(sourceFile);
		if (!source.exists())
		{
			AlertDialog.showAndWait(
				"Source File Not Found",
				"The backup file does not exist.",
				"Path: " + sourceFile + "\n\n" +
				"Please select an existing backup file to restore.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		if (!source.isFile())
		{
			AlertDialog.showAndWait(
				"Invalid Source File",
				"The selected source is not a file.",
				"Path: " + sourceFile + "\n\n" +
				"Please select a valid backup file (not a directory).",
				Alert.AlertType.ERROR
			);
			return false;
		}

		// Check required database connection parameters
		if (host == null || host.trim().isEmpty())
		{
			AlertDialog.showAndWait(
				"Missing Host",
				"",
				"Please enter the PostgreSQL host address.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		if (database == null || database.trim().isEmpty())
		{
			AlertDialog.showAndWait(
				"Missing Database Name",
				"",
				"Please enter the database name to restore to.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		if (username == null || username.trim().isEmpty())
		{
			AlertDialog.showAndWait(
				"Missing Username",
				"",
				"Please enter the PostgreSQL username.",
				Alert.AlertType.ERROR
			);
			return false;
		}

		// Validate port number
		try
		{
			int portNum = Integer.parseInt(port);
			if (portNum < 1 || portNum > 65535)
			{
				AlertDialog.showAndWait(
					"Invalid Port",
					"Port must be between 1 and 65535.",
					"Current value: " + port,
					Alert.AlertType.ERROR
				);
				return false;
			}
		}
		catch (NumberFormatException e)
		{
			AlertDialog.showAndWait(
				"Invalid Port",
				"Port must be a valid number.",
				"Current value: " + port,
				Alert.AlertType.ERROR
			);
			return false;
		}

		return true;
	}

	/** Populates the UI fields with the values from the config file */
	private void populateFields()
	{
		// Populate restore fields
		tfRestoreExecutable.setText(postgresExecutable);
		tfBackupFile.setText(postgresSourceFile);
		tfHost      .setText(postgresHost);
		tfPort      .setText(postgresPort);
		tfDatabase  .setText(postgresDatabase);
		tfUsername  .setText(postgresUsername);
		pfPassword.setText(postgresPassword);
	}

	/** Save current field values back to config file */
	private void saveToConfig()
	{
		log.debug("saving configuration to file");
		if (configSource != null)
		{
			log.debug("saving configuration to file {}", configSource.getName());

			configSource.setProperty(POSTGRES_RESTORE_EXECUTABLE_KEY, tfRestoreExecutable.getText());
			configSource.setProperty(POSTGRES_RESTORE_FILE_KEY    , tfBackupFile.getText());
			configSource.setProperty(POSTGRES_RESTORE_HOST_KEY    , tfHost      .getText());
			configSource.setProperty(POSTGRES_RESTORE_PORT_KEY    , tfPort      .getText());
			configSource.setProperty(POSTGRES_RESTORE_DATABASE_KEY, tfDatabase  .getText());
			configSource.setProperty(POSTGRES_RESTORE_USERNAME_KEY, tfUsername  .getText());
			configSource.setProperty(POSTGRES_RESTORE_PASSWORD_KEY, pfPassword.getText());

			log.info("configuration saved to file {}", configSource.getName());
		}
	}
}
