package de.ruu.lib.fx.comp.demo.hierarchy.sub2;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.05.17 12:57:18:221
 */
public interface HierarchyDemoSub2Service
{
}