package de.ruu.lib.fx.comp.demo.hierarchy.sub2;

import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import de.ruu.lib.fx.comp.demo.hierarchy.sub1.HierarchyDemoSub1;
import de.ruu.lib.fx.comp.demo.hierarchy.sub1.HierarchyDemoSub1Service;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.05.17 12:57:18:222
 */
public class HierarchyDemoSub2Controller extends DefaultFXCController<HierarchyDemoSub1, HierarchyDemoSub1Service>
{
	@Override protected void initialize() { }
}