package de.ruu.lib.fx.comp.demo.hierarchy.sub2;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link HierarchyDemoSub2App}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.05.17 12:57:18:233
 */
public class HierarchyDemoSub2App extends FXCApp
{
}