package de.ruu.lib.fx.comp.demo.empty;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link EmptyApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.05.25 17:20:51:898
 */
public class EmptyApp extends FXCApp
{
}