package de.ruu.lib.fx.comp.demo.empty;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link Empty}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.05.25 17:20:51:855
 */
public class Empty extends DefaultFXCView<Empty, EmptyService, EmptyController> { }