package de.ruu.lib.fx.comp.demo.empty;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.05.25 17:20:51:875
 */
public interface EmptyService extends FXCService { }