package de.ruu.lib.fx.comp.demo.empty;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link EmptyAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.05.25 17:20:51:913
 */
@Slf4j
class EmptyAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting EmptyAppRunner.class.getName()");
		FXCAppRunner.run(EmptyApp.class, args);
		log.debug("finished EmptyAppRunner.class.getName()");
	}
}