package de.ruu.lib.fx.comp.demo.empty;

import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.05.25 17:20:51:878
 */
class EmptyController extends DefaultFXCController<Empty, EmptyService> implements EmptyService
{
	@Override protected void initialize() { }
}