package de.ruu.lib.fx.comp.demo.empty;

import de.ruu.lib.fx.comp.FXCAppRunner;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Java FX Component Application Runner {@link EmptyAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.05.25 17:20:51:913
 */
class EmptyAppRunner extends FXCAppRunner
{
	private static final Logger log = LoggerFactory.getLogger(EmptyAppRunner.class);

	public static void main(String[] args)
	{
		log.debug("starting EmptyAppRunner.class.getName()");
		FXCAppRunner.run(EmptyApp.class, args);
		log.debug("finished EmptyAppRunner.class.getName()");
	}
}